name: Docker Image CI

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: |
            ghcr.io/edirom/cartographer-app
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}
         # and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
    - name: build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
              BUILDTYPE=github
    - name: deploy
      run: | 
        curl -X POST https://keel1.edirom.de/v1/webhooks/native -H 'Content-Type: application/json' -d '{"name": "ghcr.io/edirom/cartographer-app", "tag": "dev"}'
